[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "rx_hqm"
version = "0.2.3"
dynamic = ["dependencies"]

[tool.pyright]
# reportOptionalMemberAccess = false
# reportOptionalSubscript = false
# reportGeneralTypeIssues = false

[tool.black]
line-length = 119

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.packages.find]
where = ["."]
include = ["hqm", "hqm_data"]

[tool.setuptools.package-data]
hqm_data = ["*.json"]
