[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "moveread-pipelines-auto-extract"
version = "0.1.11"
authors = [
  {name="Marcel Claramunt", email="marcel@moveread.com"}
]
description = "Auto-extraction Moveread pipeline"
dependencies = [
  "pure-cv", "robust-extraction", "moveread-annotations", "pydantic==2.*",
  "haskellian", "queue-api", "lazy-loader", "pipeteer"
]
requires-python = ">=3.10"
readme = {file="README.md", content-type="text/markdown"}

[project.urls]
repo = "https://github.com/moveread/moveread-pipelines.git"

# [project.optional-dependencies]
# test = [
#   "pytest < 5.0.0",
#   "pytest-cov[all]"
# ]