[tool.poetry]
name = "opencf"
packages = [
    {include = "opencf"}
]
version = "0.3.3a1"
description = "A collection of Python scripts for file conversion tasks, built on top of the opencf-core framework."
authors = ["Hermann Agossou <agossouhermann7@gmail.com>"]
readme = "README.md"
maintainers = [
    "Hermann Agossou <agossouhermann7@gmail.com>"
]
license = "MIT"
homepage = "https://github.com/Hermann-web/opencf"
repository = "https://github.com/Hermann-web/opencf"
documentation = "https://opencf.readthedocs.io"
keywords = ["file conversion", "data processing", "file formats"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "License :: OSI Approved :: MIT License",
]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
opencf-core = "^0.3.2"
generalimport = "==0.5.2"
numpy = {version = "^1.24.0", optional = true}
opencv-python = {version = "^4.8.1.78", optional = true}
pillow = {version = "^10.3.0", optional = true}
pypdf = {version = "^4.2.0", optional = true}
pandas = {version = "^2.0.0", optional = true}
imageio = {version = "^2.30.0", optional = true}
pdf2docx = {version = "^0.5.8", optional = true}
aspose-words = {version = "^24.4.0", optional = true}
svgtrace = {version = "^2024", optional = true}
openpyxl = {version = "^3.1.3", optional = true}
pymupdf = {version = "^1.24.5", optional = true}


[tool.poetry.extras]
document = ["aspose-words", "pdf2docx", "pypdf", "pymupdf"]
media = ["numpy", "opencv-python", "pillow", "imageio", "svgtrace"]
tabular = ["pandas", "openpyxl"]

[tool.poetry.group.dev.dependencies]
black = "^24.3.0"
isort = "^5.13.2"
pydeps = "^1.10.0"
flake8 = "^7.0.0"
toml = "^0.10.2"
pylint = "^3.1.0"
mypy = "^1.10.0"
pandas-stubs = "^2.2.2.240514"
types-openpyxl = "^3.1.2.20240601"

[tool.poetry.group.buildthedocs.dependencies]
sphinx = "^7.0.0"
sphinx-rtd-theme = "^2.0.0"
m2r2 = "^0.3.3.post2"

[tool.isort]
profile = "black"

[tool.black]
line-length = 88

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
opencf = "opencf.app:main"
