[tool.poetry]
name = "jenfi-pipeline-data-app"
version = "0.5.5"
description = ""
readme = "README.md"
authors = ["Justin Louie <224840+nitsujri@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "~3.10"
SQLAlchemy = "^1.4.40"
numpy = "^1.23.2"
python-dotenv = "^0.20.0"
psycopg2 = "^2.9.3"
pandas = "2.2"
boto3 = "^1.24.78"
sqlparse = "^0.4.2"
scikit-learn = "^1.1.2"
sagemaker = "^2.150.0"
statsmodels = "^0.13.5"
jupyterlab-git = "^0.41.0"
levenshtein = "^0.21.0"
catboost = "^1.2.3"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
pytest = "^7.1.3"
pdoc3 = "^0.10.0"
papermill = "^2.4.0"
jupyterlab = "^3.4.7"

[tool.poetry.scripts]
pipeline-data-app = 'pipeline_data_app:main'

[tool.poetry.group.dev.dependencies]
pytest-env = "^0.8.1"
pre-commit = "^3.3.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
env = [
  "D:PYTHON_ENV=test"
]
# addopts = "--capture='no'"
testpaths = ['tests']
