[project]
name = "supplies"
version = "0.2.4"
authors = [
  { name="左易晗(from china)", email="19156653620@163.com" },
]
description = "Parameters supply."
readme = "README.md"
requires-python = ">=3.1"
keywords = ["suuplies", "supply", "parmas", "crawler"]
dependencies = ["requests >= 2.31.0"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
