[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "fuel_efficiency_joeljunior95"
version = "0.0.2"
authors = [
  { name="Joel Souza", email="joel.junior.95@gmail.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.10.4"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/joeljunior95/fuel_efficiency"
Issues = "https://github.com/joeljunior95/fuel_efficiency/issues"