[project]
name = "dektools"
version = "0.1.117"
description = ""
authors = [
    { name = "sanzenwin", email = "sanzenwin@gmail.com" },
]
dependencies = [
    "igittigitt<=2.0.4",
    "pyyaml<=6.0.1",
    "yamlloader<=1.3.2",
    "pybase62<=1.0.0",
    "typer<=0.9.0",
    "tzdata>=2022.7",
    "RestrictedPython<=5.2",
    "snowflake-id<=0.0.5",
    "asgiref<4",
    "dynaconf<=3.2.4",
    "jsonpath-ng<=1.6.1",
]
requires-python = ">=3.10"
readme = "README.md"

[project.license]
text = "MIT"

[project.optional-dependencies]
crypto = [
    "pycryptodome<=3.18.0",
]

[project.scripts]
dektools = "dektools.click.__entry__:main"

[tool.pdm.build]
includes = [
    "dektools",
]

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"
